Production.jenkinsfile is finished
IT IS TO ITS BIGGEST IMPORTANCE TO TO MAKE THE PIPELINE WORK THAT THE JENKINS USER ON THE JENKINS SERVER HAS HAD A SSH CONNECTION TO THE PROD SERVER.

diff --git a/production.jenkinsfile b/production.jenkinsfile
--- a/production.jenkinsfile
+++ b/production.jenkinsfile
@@ -1,9 +1,60 @@
 pipeline {
     agent any
+    
+    environment {
+        PROD_SERVER = '54.166.141.254'
+        SSH_CREDENTIALS_ID = '239a38a7-6643-4bc6-85b8-7272fff21765'
+        DOCKER_IMAGE = 'tommyquatretempspxl/dtap'
+        CONTAINER_NAME = 'calculator-app'
+    }
+// IMPORTANT FOR SSHAGENT TO WORK THE JENKINS USER NEEDS TO HAVE SSHED ONCE BEFORE WITH THE PROD SERVER
     stages {
-        stage('dtap production') {
+        stage('Cleanup Prod') {
             steps {
-                echo "good luck..."
+                sshagent([SSH_CREDENTIALS_ID]) { 
+                    sh '''
+                    ssh ubuntu@${PROD_SERVER} "
+                    docker rm -f ${CONTAINER_NAME} || true
+                    "
+                    '''
+                }
+            }
+        }
+
+        stage('Deploy Prod') {
+            steps {
+                sshagent([SSH_CREDENTIALS_ID]) { 
+                    sh '''
+                    ssh ubuntu@${PROD_SERVER} "
+                    docker pull ${DOCKER_IMAGE}
+                    "
+                    '''
+                }
+            }
+        }
+        
+        stage('Start Prod') {
+            steps {
+                sshagent([SSH_CREDENTIALS_ID]) {
+                    sh '''
+                    ssh ubuntu@${PROD_SERVER} "
+                    docker run -d -p 80:3000 --name ${CONTAINER_NAME} ${DOCKER_IMAGE}
+                    "
+                    '''
+                }
+            }
+        }
+        
+        stage('Test Prod') {
+            steps {
+                script {
+                    def response = sh(script: "curl -o /dev/null -s -w \"%{http_code}\" http://${PROD_SERVER}", returnStdout: true).trim()
+                    if (response != '200') {
+                        error "Production deployment failed. HTTP status code: ${response}"
+                    } else {
+                        echo "Production deployment succeeded. HTTP status code: ${response}"
+                    }
+                }
             }
         }
     }
